config/routes.rb
Rails.application.routes.draw do

  get 'test_html/index'

  resources :dashboards

  devise_for :users

  resources :users do
    resources :user_activities, except: [:create, :new]
    resources :user_prizes
  end

  resources :activities do
    resources :user_activities, only: [:create, :new]
  end



  get "self" => 'activities#self', as: 'self'
  get "train" => 'activities#train', as: 'train'
  get "responsibility" => 'activities#responsibility', as: 'responsibility'
  get "opportunities" => 'activities#opportunities', as: 'opportunities'
  get "numbers" => 'activities#numbers', as: 'numbers'
  get "goals" => 'activities#goals', as: 'goals'
  get "new_user_activity" => 'user_activities#new', as: 'new_user_activities'

  resources :prizes
  resources :activities


  namespace :admin do
    resources :prizes
    resources :activities 
    resources :users 
  end


  root to: 'dashboards#index'

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
    belongs_to :user
    belongs_to :activity
    validates :user_id, :activity_id, presence: true

end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController
  before_action :get_user_activity, only: [:show, :edit, :update, :delete]
  before_action :get_user


  def index
    ws = Date.today.at_beginning_of_week
    sun = ws - 1
    mon = sun + 1
    tue = mon + 1
    wed = tue + 1
    thu = wed + 1
    fri = thu + 1
    sat = fri + 1

    @sun_activities = UserActivity.where("completion_date = ? AND user_id = ?", sun, @user).joins(:activity).order('activities.wellness_type')
    @mon_activities = UserActivity.where("completion_date = ? AND user_id = ?", mon, @user).joins(:activity).order('activities.wellness_type')
    @tue_activities = UserActivity.where("completion_date = ? AND user_id = ?", tue, @user).joins(:activity).order('activities.wellness_type')
    @wed_activities = UserActivity.where("completion_date = ? AND user_id = ?", wed, @user).joins(:activity).order('activities.wellness_type')
    @thu_activities = UserActivity.where("completion_date = ? AND user_id = ?", thu, @user).joins(:activity).order('activities.wellness_type')
    @fri_activities = UserActivity.where("completion_date = ? AND user_id = ?", fri, @user).joins(:activity).order('activities.wellness_type')
    @sat_activities = UserActivity.where("completion_date = ? AND user_id = ?", sat, @user).joins(:activity).order('activities.wellness_type')

  end

  def show
  end

  def new
    @activity = Activity.find(params[:activity_id])
    @user_activity = UserActivity.new(user: @user, activity: @activity)

  end

  def create
    @activity = Activity.find(params[:activity_id])
    @user_activity = UserActivity.new(user_activity_params)
    @user_activity.user = @user

    if @user_activity.save
      redirect_to :action => 'show', id: @user_activity.id, user_id: @user.id
    else
      redirect_to :action => 'index', user_id: @user.id
    end
  end

  def edit
  end

  def update
    @user_activity.update(user_activity_params)
    @user_activity.save
  end
  def delete
  end

  def get_user
    user_id = params[:user_id] || current_user.id
    @user =  User.find(user_id)
  end

  def user_activity_params
    params.require(:user_activity).permit(:user_id, :description, :activity_id, :image_path, :completion_date)
  end


  def get_user_activity
    @user_activity = UserActivity.find(params[:id])

  end
end

app/helpers/user_activities_helper.rb
module UserActivitiesHelper
end

app/views/user_activities/_this_week.html.haml
-@week_activities.each do |r|

app/views/user_activities/index.html.haml
%h5
  %strong{style: 'color: rgb(195,195,195); padding-left: 10%;'} ACTIVITY LOG
%h2{style: 'padding-left: 10%;'} This Week

.week-container

  %h3 Sunday
  .container{:style=>"overflow-x: auto;"}
    -if @sun_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"
    %table

      -@sun_activities.each do |s|
        %tr
          -activity = Activity.find(s.activity_id)
          %td.img-col
            =image_tag(activity.icon_path, height: '32', width: '32') || ""
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"

  %h3 Monday
  .container{:style=>"overflow-x: auto;"}

    -if @mon_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"
    %table
      - @mon_activities.each do |m|
        %tr
          -activity = Activity.find(m.activity_id)
          %td.img-col
            =image_tag(activity.icon_path, height: '32', width: '32') || ""
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"

  %h3 Tuesday
  .container{:style=>"overflow-x: auto;"}
    -if @tue_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"
    %table
      -@tue_activities.each do |t|
        %tr
          -activity = Activity.find(t.activity_id)
          %td.img-col
            =image_tag(activity.icon_path, height: '32', width: '32') || ""
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"

  %h3 Wednesday
  .container{:style=>"overflow-x: auto;"}
    -if @wed_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"
    %table
      -@wed_activities.each do |w|
        %tr
          %td.img-col
          -activity = Activity.find(w.activity_id)
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"
  %h3 Thursday
  .container{:style=>"overflow-x: auto;"}
    -if @thu_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"

    %table
      -@thu_activities.each do |h|
        %tr
          %td.img-col
            =image_tag(activity.icon_path, height: '32', width: '32') || ""
          -activity = Activity.find(h.activity_id)
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"

  %h3 Friday
  .container{:style=>"overflow-x: auto;"}
    -if @fri_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"
    %table
      -@fri_activities.each do |f|
        %tr
          %td.img-col
          -activity = Activity.find(f.activity_id)
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"

  %h3 Saturday
  .container{:style=>"overflow-x: auto;"}
    -if @sat_activities.empty? == true
      No activities logged yet.
      = link_to 'Log Activities' , activities_path, :class=>"btn btn-default", :role=>"button"
    %table
      -@sat_activities.each do |a|
        %tr
          %td.img-col
            =image_tag(activity.icon_path, height: '32', width: '32') || ""
          -activity = Activity.find(a.activity_id)
          %td
            =activity.title
          %td
            =activity.description
          %td
            ="#{activity.point_value} Points"

app/views/user_activities/new.html.haml
.every-header
  %h5
    %strong{style: 'color: rgb(195,195,195); padding-left: 10%;'} RECORD ACTIVITIES
  %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(93, 93, 93); '} Log the details of your activity.
  %br
.pop-container
  -if @activity.image_path.blank? == false
    =image_tag(@activity.image_path, height: '50', width: 'auto')
  =@activity.title

  = simple_form_for @user_activity, :method => :post, :url => activity_user_activities_path do |f|
    =f.date_select :completion_date
    =f.hidden_field :activity_id, :value => @activity.id

    =f.button :submit, :value => 'LOG ACTION'

app/views/user_activities/show.html.haml
%h1 Activity Added
-activity = Activity.find(@user_activity.activity_id)
=activity.title
=activity.description