config/routes.rb
Rails.application.routes.draw do

  get 'test_html/index'

  resources :dashboards

  devise_for :users

  resources :users do
    resources :user_activities, except: [:create, :new]
    resources :user_prizes
  end

  resources :activities do
    resources :user_activities, only: [:create, :new]
  end



  get "self" => 'activities#self', as: 'self'
  get "train" => 'activities#train', as: 'train'
  get "responsibility" => 'activities#responsibility', as: 'responsibility'
  get "opportunities" => 'activities#opportunities', as: 'opportunities'
  get "numbers" => 'activities#numbers', as: 'numbers'
  get "goals" => 'activities#goals', as: 'goals'
  get "new_user_activity" => 'user_activities#new', as: 'new_user_activities'

  resources :prizes
  resources :activities


  namespace :admin do
    resources :prizes
    resources :activities 
    resources :users 
  end


  root to: 'dashboards#index'

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord

  validates :title, :description, :image_path, :point_value, :activity_status, :strong_type, :wellness_type, :icon_path, presence: true
  mount_uploader :image_path, ImageUploader

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/prize.rb
class Prize < ApplicationRecord
  validates :title, :description, :image_path, :point_value, :activity_status, :quantity, presence: :true
  mount_uploader :image_path, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_prizes
  has_many :user_activities
  accepts_nested_attributes_for :user_prizes, :user_activities, allow_destroy: true, reject_if: :all_blank


  def update_points(points)
    self.points = self.points + points
    self.save
  end

end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
    belongs_to :user
    belongs_to :activity
    validates :user_id, :activity_id, presence: true

end

app/models/user_date.rb
class User_Date
  attr_accessor :month, :day, :year

  def initialize
    @month = DateTime.now.strftime('%m')
    @day = DateTime.now.strftime('%d')
    @year = DateTime.now.strftime('%Y')
  end
end

app/models/user_prize.rb
class UserPrize < ApplicationRecord
    belongs_to :user
    belongs_to :prize
    validates :user_id, :prize_id, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_filter :authorized?

  private
  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to root_path
    end
  end


end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  def index
    @prizes = Prize.find_each
    @user = current_user
  end
  def show
    @prize = Prize.find(params[:id])

  end
  def new
    @prize = Prize.new
  end
  def create
    @prize = Prize.new(prize_params)


    if @prize.save
      redirect_to action: 'show', id: @prize.id
    else
      pp @prize.errors.full_messages
      flash[:alert] = "nope"
      redirect_to action: 'new'
    end
  end
  def edit
    @prize = Prize.find(params[:id])
  end
  def update
    @prize = Prize.find(params[:id])
    @prize.update(prize_params)
    @prize.save
  end
  def destroy
    @prize = Prize.delete(params[:id])
  end
  def prize_params
    params.require(:prize).permit(:title, :description, :image_path, :point_value, :activity_status, :quantity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit, :update, :delete, :add_user_prizes, :add_user_activities]

  def index
  end
  def show

  end
  def new
  end
  def show_user_prizes
  end
  def show_user_activities
  end
  def create
  end
  def edit
  end
  def add_user_prizes
    @prizes = Prize.find_each
    @user.current_proc = "_add_user_prizes"
  end
  def add_user_activities
    @activities = Activity.find_each
    @user.current_proc = "_add_user_activities"
    redirect_to :edit
  end
  def update
    @user.update(user_params)
    if params[:user_prize_attributes][:prize_id] != ""
      make_user_prize
      redirect_to :show_user_prizes
    elsif params[:user_activity_attributes][:activity_id] != ""
      make_user_activity

    end
  end
  def delete
  end


  def user_params
    params.require(:user).permit(:name, :age_group, user_activity_attributes: [:activity_id, :image_path],
                                      user_prize_attributes: [:prize_id])

  end

  def get_user
    @user = User.find(params[:id])
  end

  def make_user_activity
    activity = Activity.find(id: params[:user_activity_attributes][:activity_id])
    point_val = activity.point_value
    @user.update_points(point_val)
  end
  def make_user_prize
    prize = Prize.find(params[:user_prize_attributes][:prize_id])
    point_val = prize.point_value * -1
    @user.update_points(point_val)
  end
  def update_user_points(points)
    @user.points = @user.points + points
    @user.save
  end
  def get_current_process

  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/test_html_helper.rb
module TestHtmlHelper
end

app/helpers/user_prizes_helper.rb
module UserPrizesHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.haml
.every-header
  %h5
    %strong{style: 'color: rgb(195,195,195); padding-left: 10%;'} RECORD ACTIVITIES
  %a   
  %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(93, 93, 93); '} Add Activities for users to participate in. 

  %br

  .list-container.container
    %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
      %li.active.responsive
        = link_to 'All', activities_path
      %li.responsive
        = link_to 'Self', self_path
      %li.responsive
        = link_to 'Train', train_path
      %li.responsive
        = link_to 'Responsibility', responsibility_path
      %li.responsive
        = link_to 'Opportunities', opportunities_path
      %li.responsive
        = link_to 'Numbers', numbers_path
      %li.responsive
        = link_to 'Goals', goals_path
    %br
    %ul.activities-list
      =@activities.each do |a|
        %li.activities-list-item
          %span.points-icon
            %span.points
              =a.point_value
          .list-image

            -if a.image_path.blank? == false
              =image_tag(a.image_path.resized )
          .caption
            %h3
              =a.title

              =image_tag(a.icon_path, height: '32', width: '32')
            %p=a.description
            .row
              .col-sm-6
              .col-sm-6
                =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/layouts/_navbar.html.haml
%nav.navbar-container.navbar-fixed-top.my-navbar
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", "data-toggle" => "collapse",
      "data-target" => "#bs-example-navbar-collapse-1", "aria-expanded" => "false"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: '/', style: 'margin-bottom: 5px'}
        =image_tag('Logo.png', height: '60', width: 'auto') || ""

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{href:"#", "data-toggle" => "dropdown", role: "button", "aria-haspopup" => "true", "aria_expanded" => "false"}
              DASHBOARD
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                =link_to "Past Actions", [current_user, :user_activities]
              %li
                =link_to "Earned Prizes", [current_user, :user_prizes]
              %li
                %a{href:"#"} Goals


          %li
            =link_to 'GET REWARDS', prizes_path
            %span.sr-only(current)
          %li
            =link_to 'EARN POINTS', activities_path

      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href:"#"} ABOUT WVAStrong
        %li.dropdown
          %a.dropdown-toggle{href:"#", "data-toggle" => "dropdown", role: "button",
          "aria-haspopup" => "true", "aria-expanded" => "false"}
            ACCOUNT
            %span.caret

          %ul.dropdown-menu

            -if user_signed_in?
              %li
                %a{href: "users/#{current_user.id}", method: "get"} Profile
              %li
                =link_to('Logout', destroy_user_session_path, method: :delete)
            -else
              %li
                =link_to('Login', new_user_session_path)

app/views/layouts/_signed_out.html.haml
#homepage
  .jumbo
    -if controller_name != "dashboards"
      =render '#{controller_name}/#{action_name}'
    -else
      .row
        .text-group
          %h1 Get Healthy.
          %h1 Win Prizes.

app/views/layouts/admin.html.haml
 %head
  %title WellnessApp
  = csrf_meta_tags
  = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'admin', 'data-turbolinks-track' => true


-if user_signed_in? == false

  -if controller_name == "dashboards"
    .homepage
      =render 'layouts/navbar'
      #homepage
        .jumbo
          .row
            .text-group
              %h1 Get Healthy.
              %h1 Win Prizes.
  -else
    =render 'layouts/navbar'
  .body-container
    -if notice
      %p.alert.alert-success= notice
    -if alert
      %p.alert.alert-danger= alert
    =yield
-else
  =render 'layouts/navbar'
  .body-container
    -if notice
      %p.alert.alert-success= notice
    -if alert
      %p.alert.alert-danger= alert
    =yield

app/views/layouts/application.html.haml
%head
  %title WellnessApp
  = csrf_meta_tags

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'




-if user_signed_in? == false

  -if controller_name == "dashboards"
    .homepage
      =render 'layouts/navbar'
      #homepage
        .jumbo
          .row
            .text-group
              %h1 Get Healthy.
              %h1 Win Prizes.
  -else
    =render 'layouts/navbar'
  .body-container
    -if notice
      %p.alert.alert-success= notice
    -if alert
      %p.alert.alert-danger= alert
    =yield
-else
  =render 'layouts/navbar'
  .body-container
    -if notice
      %p.alert.alert-success= notice
    -if alert
      %p.alert.alert-danger= alert
    =yield