config/routes.rb
Rails.application.routes.draw do

  get 'test_html/index'

  resources :dashboards

  devise_for :users

  resources :users do
    resources :user_activities, except: [:create, :new]
    resources :user_prizes
  end

  resources :activities do
    resources :user_activities, only: [:create, :new]
  end



  get "self" => 'activities#self', as: 'self'
  get "train" => 'activities#train', as: 'train'
  get "responsibility" => 'activities#responsibility', as: 'responsibility'
  get "opportunities" => 'activities#opportunities', as: 'opportunities'
  get "numbers" => 'activities#numbers', as: 'numbers'
  get "goals" => 'activities#goals', as: 'goals'
  get "new_user_activity" => 'user_activities#new', as: 'new_user_activities'

  resources :prizes
  resources :activities


  namespace :admin do
    resources :prizes
    resources :activities 
    resources :users 
  end


  root to: 'dashboards#index'

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord

  validates :title, :description, :image_path, :point_value, :activity_status, :strong_type, :wellness_type, :icon_path, presence: true
  mount_uploader :image_path, ImageUploader

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :get_activity, only: [:show, :edit, :update, :destroy]
  before_action :get_user

  def index
    @activities = Activity.find_each
  end
  def show

  end
  def new
    @activity = Activity.new()

  end
  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      @activities = Activity.find_each
      render 'index'
    else
    end

  end
  def edit
    get_activity
    puts @activity
    $stdout.flush
  end
  def update
    @activity.update(activity_params)
    @activity.save
    render 'show'
  end
  def destroy
    @activity.destroy
    flash[:success] = "Activity Deleted"
    redirect_to activities_url
  end
  def self
    @self_activities = Activity.where(:strong_type => 'Self').find_each
  end
  def train
    @train_activities = Activity.where(:strong_type => 'Train').find_each

  end
  def responsibility
    @resp_activities = Activity.where(:strong_type => 'Responsibility').find_each

  end
  def opportunities
    @opp_activities = Activity.where(:strong_type => 'Opportunities').find_each

  end
  def numbers
    @num_activities = Activity.where(:strong_type => 'Numbers').find_each

  end
  def goals
    @goals_activities = Activity.where(:strong_type => 'Goals').find_each

  end

  def activity_params
    params.require(:activity).permit(:title, :description, :image_path, :point_value, :activity_status, :strong_type, :wellness_type, :icon_path)
  end

  def get_activity
    @activity = Activity.find(params[:id])
  end
  def get_user
    @user = current_user
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < AdminController
  before_action :get_activity, only: [:show, :edit, :update, :destroy]
  before_action :get_user

  def index
    @activities = Activity.find_each
  end
  def show

  end
  def new
    @activity = Activity.new()

  end
  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      @activities = Activity.find_each
      render 'index'
    else
    end

  end
  def edit
    get_activity
    puts @activity
    $stdout.flush
  end
  def update
    @activity.update(activity_params)
    @activity.save
    render 'show'
  end
  def destroy
    @activity.destroy
    flash[:success] = "Activity Deleted"
    redirect_to activities_url
  end
  def self
    @self_activities = Activity.where(:strong_type => 'Self').find_each
  end
  def train
    @train_activities = Activity.where(:strong_type => 'Train').find_each

  end
  def responsibility
    @resp_activities = Activity.where(:strong_type => 'Responsibility').find_each

  end
  def opportunities
    @opp_activities = Activity.where(:strong_type => 'Opportunities').find_each

  end
  def numbers
    @num_activities = Activity.where(:strong_type => 'Numbers').find_each

  end
  def goals
    @goals_activities = Activity.where(:strong_type => 'Goals').find_each

  end

  def activity_params
    params.require(:activity).permit(:title, :description, :image_path, :point_value, :activity_status, :strong_type, :wellness_type, :icon_path)
  end

  def get_activity
    @activity = Activity.find(params[:id])
  end
  def get_user
    @user = current_user
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/all_search.html.haml
%h1 Record Your Activities
.container
  %ul.nav.nav-tabs
    %li.active
      = link_to 'All', activities_path
    %li
      = link_to 'Overall Health', overall_path
    %li
      = link_to 'Fitness', fitness_path
    %li
      = link_to 'Nutrition', nutrition_path
    %li
      = link_to 'WVA Events', wva_events_path


%br
.row
  =@all_activities.each do |a|
    .col-sm-6.col-md-4
      .thumbnail
        .caption
          %h3=a.title
          %p=a.description
          %p
            -#%a{:href =>edit_activity_path(a), :class=>"btn btn-primary", :role=>"button" } Edit
            -#%a{:href=>"#", :class=>"btn btn-default", :role=>"button"}Delete
            =link_to "Add This Action", {controller: 'user_activities', action: 'create', id: @user.id, activity: a.id }, method: 'post', :class=>"btn btn-default", :role=>"button"

      %br

app/views/activities/edit.html.haml
%h1 Edit Action
= simple_form_for @activity, :method => :patch, :url => activity_path(@activity.id) do |f|
  = f.input :title, :label => 'Title'
  = f.input :description, :as => :text, :label => 'Description'
  = f.file_field :image_path
  = f.input :point_value, :label => 'Point Value'
  = f.input :activity_status, :collection => [ 'A','I','D' ], :label => 'Status(Active,Inactive,Deleted)'
  = f.input :strong_type, :collection => ['Self', 'Train', 'Responsibility','Opportunities','Numbers','Goals'], :label => 'STRONG Category'
  = f.input :wellness_type, :collection => ['Nutrition', 'Fitness', 'Overall Health', 'WVA Event'], :label => 'Wellness Category'
  = f.input :icon_path, :collection => ['Self-Icon.png', 'Train-Icon.png', 'Responsibility-Icon.png', 'Opportunity-Icon.png', 'Numbers-Icon.png', 'Goals-Icon.png']
  = f.button :submit

app/views/activities/goals.html.haml
.every-header.lime-green.row
  .col-sm-10
    %h5
      %strong{style: ' padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(240,240,240) '} Add a GOALS activity to your personal Activity Log by choosing from a list of healthy options.
  .col-sm-2
    =image_tag("Goals-Icon.png",height: '110', width: '110' )
.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.responsive
      = link_to 'All', activities_path
    %li.responsive
      = link_to 'Self', self_path
    %li.responsive
      = link_to 'Train', train_path
    %li.responsive
      = link_to 'Responsibility', responsibility_path
    %li.responsive
      = link_to 'Opportunities', opportunities_path
    %li.responsive
      = link_to 'Numbers', numbers_path
    %li.active.responsive
      = link_to 'Goals', goals_path
  %br
  %ul.activities-list
    =@goals_activities.each do |a|
      %li.activities-list-item
        %span.points-icon
          %span.points
            =a.point_value
        .list-image
          -if a.image_path.blank? == false
            =image_tag(a.image_path.resized)
        .caption
          %h3
            =a.title

            =image_tag("Goal-Icon.png", height: '32', width: '32')
          %p=a.description
          .row
            .col-sm-6
            .col-sm-6
              =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/activities/index.html.haml
.every-header.row
  .col-sm-9
    %h5
      %strong{style: 'color: rgb(195,195,195); padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(93, 93, 93); '} Add an activity to your personal Activity Log by choosing from a list of healthy options.
  .col-sm-3.icons-list
    %span=image_tag("Self-Icon.png", height: '50', width:'50')
    %span=image_tag("Train-Icon.png", height: '50', width:'50')
    %span=image_tag("Responsibility-Icon.png", height: '50', width:'50')
    %span=image_tag("Opportunity-Icon.png", height: '50', width:'50')
    %span=image_tag("Numbers-Icon.png", height: '50', width:'50')
    %span=image_tag("Goals-Icon.png", height: '50', width:'50')

.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.active.responsive
      = link_to 'All', activities_path
    %li.responsive
      = link_to 'Self', self_path
    %li.responsive
      = link_to 'Train', train_path
    %li.responsive
      = link_to 'Responsibility', responsibility_path
    %li.responsive
      = link_to 'Opportunities', opportunities_path
    %li.responsive
      = link_to 'Numbers', numbers_path
    %li.responsive
      = link_to 'Goals', goals_path
  %br
  %ul.activities-list
    =@activities.each do |a|
      %li.activities-list-item
        %span.points-icon
          %span.points
            =a.point_value
        .list-image

          -if a.image_path.blank? == false
            =image_tag(a.image_path.resized )
        .caption
          %h3
            =a.title

            =image_tag(a.icon_path, height: '32', width: '32')
          %p=a.description
          .row
            .col-sm-6
            .col-sm-6
              =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/activities/new.html.haml
%h1 New Action
= simple_form_for @activity,:method => :post do |f|
  = f.input :title, :label => 'Title'
  = f.input :description, :as => :text, :label => 'Description'
  = f.file_field :image_path
  = f.input :point_value, :label => 'Point Value'
  = f.input :activity_status, :collection => [ 'A','I','D' ], :label => 'Status(Active,Inactive,Deleted)'
  = f.input :strong_type, :collection => ['Self', 'Train', 'Responsibility','Opportunities','Numbers','Goals'], :label => 'STRONG Category'
  = f.input :wellness_type, :collection => ['Fitness', 'Nutrition', 'Overall Health', 'WVA Event']
  = f.input :icon_path, :collection => ['apple.png', 'Weightlifting.png', 'mind.png', 'heart.png']
  = f.button :submit

app/views/activities/numbers.html.haml
.every-header.blue.row
  .col-sm-10
    %h5
      %strong{style: ' padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(240,240,240) '} Add a NUMBERS activity to your personal Activity Log by choosing from a list of healthy options.
  .col-sm-2
    =image_tag("Numbers-Icon.png",height: '110', width: '110' )
.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.responsive
      = link_to 'All', activities_path
    %li.responsive
      = link_to 'Self', self_path
    %li.responsive
      = link_to 'Train', train_path
    %li.responsive
      = link_to 'Responsibility', responsibility_path
    %li.responsive
      = link_to 'Opportunities', opportunities_path
    %li.active.responsive
      = link_to 'Numbers', numbers_path
    %li.responsive
      = link_to 'Goals', goals_path
  %br
  %ul.activities-list
    =@num_activities.each do |a|
      %li.activities-list-item
        %span.points-icon
          %span.points
            =a.point_value
        .list-image

          -if a.image_path.blank? == false
            =image_tag(a.image_path.resized)
        .caption
          %h3
            =a.title

            =image_tag("Numbers-Icon.png", height: '32', width: '32')
          %p=a.description
          .row
            .col-sm-6
            .col-sm-6
              =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/activities/opportunities.html.haml
.every-header.red.row
  .col-sm-10
    %h5
      %strong{style: ' padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(240,240,240) '} Add an OPPORTUNITY activity to your personal Activity Log by choosing from a list of healthy options.
  .col-sm-2
    =image_tag("Opportunity-Icon.png",height:'110',width:'110')
.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.responsive
      = link_to 'All', activities_path
    %li.responsive
      = link_to 'Self', self_path
    %li.responsive
      = link_to 'Train', train_path
    %li.responsive
      = link_to 'Responsibility', responsibility_path
    %li.active.responsive
      = link_to 'Opportunities', opportunities_path
    %li.responsive
      = link_to 'Numbers', numbers_path
    %li.responsive
      = link_to 'Goals', goals_path
  %br
  %ul.activities-list
    =@opp_activities.each do |a|
      %li.activities-list-item
        %span.points-icon
          %span.points
            =a.point_value
        .list-image

          -if a.image_path.blank? == false
            =image_tag(a.image_path.resized)
        .caption
          %h3
            =a.title

            =image_tag("Opportunity-Icon.png", height: '32', width: '32')
          %p=a.description
          .row
            .col-sm-6
            .col-sm-6
              =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/activities/responsibility.html.haml
.every-header.orange.row
  .col-sm-10

    %h5
      %strong{style: ' padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(240,240,240);'} Add an activity to your personal Activity Log by choosing from a list of healthy options.

  .col-sm-2
    =image_tag("Responsibility-Icon.png",height: '110', width: '110' )

.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.responsive
      = link_to 'All', activities_path
    %li.responsive
      = link_to 'Self', self_path
    %li.responsive
      = link_to 'Train', train_path
    %li.active.responsive
      = link_to 'Responsibility', responsibility_path
    %li.responsive
      = link_to 'Opportunities', opportunities_path
    %li.responsive
      = link_to 'Numbers', numbers_path
    %li.responsive
      = link_to 'Goals', goals_path
  %br
  %ul.activities-list
    =@resp_activities.each do |a|
      %li.activities-list-item
        %span.points-icon
          %span.points
            =a.point_value
        .list-image
          -if a.image_path.blank? == false
            =image_tag(a.image_path.resized)
        .caption
          %h3
            =a.title

            =image_tag("Responsibility-Icon.png", height: '32', width: '32')
          %p=a.description
          .row
            .col-sm-6
            .col-sm-6
              =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/activities/self.html.haml
.every-header.purple.row
  .col-sm-10
    %h5
      %strong{style:' padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(240,240,240); '} Add a SELF activity to your personal Activity Log by choosing from a list of healthy options.
  .col-sm-2
    =image_tag("Self-Icon.png",height: '110', width: '110' )

.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.responsive
      = link_to 'All', activities_path
    %li.active.responsive
      = link_to 'Self', self_path
    %li.responsive
      = link_to 'Train', train_path
    %li.responsive
      = link_to 'Responsibility', responsibility_path
    %li.responsive
      = link_to 'Opportunities', opportunities_path
    %li.responsive
      = link_to 'Numbers', numbers_path
    %li.responsive
      = link_to 'Goals', goals_path
  %br
    %ul.activities-list
      =@self_activities.each do |a|
        %li.activities-list-item
          %span.points-icon
            %span.points
              =a.point_value
          .list-image
            -if a.image_path.blank? == false
              =image_tag(a.image_path.resized)
          .caption
            %h3
              =a.title

              =image_tag("Self-Icon.png", height: '32', width: '32')
            %p=a.description
            .row
              .col-sm-6
              .col-sm-6
                =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"

app/views/activities/show.html.haml
=@activity.title
%br
=@activity.description
%br
%br
=link_to "Back", :back
|
=link_to "Edit", edit_activity_path(@activity)
|
=link_to "Delete", @activity, method: :delete, data: {confirm: "You sure?" }

app/views/activities/train.html.haml
.every-header.yellow.row
  .col-sm-10

    %h5
      %strong{style: ' padding-left: 10%;'} RECORD ACTIVITIES
    %h2{style: 'padding-left: 10%; max-width: 26em; margin-bottom: 5%; color: rgb(240,240,240);'} Add a TRAIN activity to your personal Activity Log by choosing from a list of healthy options.

  .col-sm-2
    =image_tag("Train-Icon.png",height: '110', width: '110' )

.list-container.container
  %ul.nav.nav-tabs.responsive{style:'max-width: 73em;' }
    %li.responsive
      = link_to 'All', activities_path
    %li.responsive
      = link_to 'Self', self_path
    %li.active.responsive
      = link_to 'Train', train_path
    %li.responsive
      = link_to 'Responsibility', responsibility_path
    %li.responsive
      = link_to 'Opportunities', opportunities_path
    %li.responsive
      = link_to 'Numbers', numbers_path
    %li.responsive
      = link_to 'Goals', goals_path
  %br
  %ul.activities-list
    =@train_activities.each do |a|
      %li.activities-list-item
        %span.points-icon
          %span.points
            =a.point_value
        .list-image

          -if a.image_path.blank? == false
            =image_tag(a.image_path.resized)
        .caption
          %h3
            =a.title
            =image_tag("Train-Icon.png", height: '32', width: '32')
          %p=a.description
          .row
            .col-sm-6
            .col-sm-6
              =link_to "LOG ACTION", [:new_activity_user_activity, activity_id: a.id, user_id: current_user.id] , :class=>"btn btn-default", :role=>"button"